### ISSUE TITLE
Get-PSTenableSeverity seems to have a max records

### ISSUE THREAD

**Issue by AaronG1234** [jwmoss/PSTenable#12]
## Expected Behavior
$Critical = Get-PSTenableSeverity -Severity "critical"
$critical.count
24438

## Current Behavior
$Critical = Get-PSTenableSeverity -Severity "critical"
$critical.count
5000

## Possible Solution
Get-PSTenableSeverity has a hard coded cap in the query hashtable that builds the json
either stop putting any cap, or have maxRecords be an [int] argument and let the user choose.

## Steps to Reproduce (for bugs)

Assuming your SC has more than 5000 critical vuln in the repository
1.if (!($creds)) {$creds = Get-Credential}
Connect-PSTenable -Credential $creds -TenableServer "https://securitycenter.xxxxx.xxxx/rest" -Register

2. $Critical = Get-PSTenableSeverity -Severity "critical"
$critical.count
5000

## Context
i have no way to use this module, and see the 5001-24000ish critical vulns i would like to see

## Your Environment

* Module version used: 0.2.3
* Operating System and PowerShell version: Win 10, 5.1

**Comment by jwmoss** [comment]
I recall that being a limit of the API, let me see if I can take a look at that again.

**Comment by AaronG1234** [comment]
I thought that when i did this raw a few months ago (with get-webrequest or something) that i was able to just get the whole dump....
but either way, if it is a "good idea" cap, then you would want to loop and paginate from 0-4999, and then 5000-9999, etc. until you got back no data...  i still stink it is a good idea to not just get all... could take forever... so thats why an argument the user could control... if they say nothing, you get everything there is... otherwise you let them determine the max records

**Comment by AaronG1234** [comment]
a have a feature request in this same function, do you want me to create a seperate issue?  (allow multiple Severitys
the API doc says a comma seperated list of Severity (in [int] format) should work.
I'd like to be able to pull Crits and Highs, etc.

**Comment by jwmoss** [comment]
Sure, feel free to submit another issue with a feature request that way I can take a look at this first, and then see if I can’t fix the feature request.

**Comment by AaronG1234** [comment]
so he first issue is that the tool vulnipdetail requires to to give it some max record...
i forked your project and ill get some code up to loop through a pagination.

**Comment by AaronG1234** [comment]
ok, i create a pull request that paginates at 5000 pages and honors multiple severities

**Comment by AaronG1234** [comment]
Updated... Dont know why your validation doesnt like it.  Im using it right now ;P
________________________________

**Comment by jwmoss** [comment]
@AaronG1234 Missing parameter help for max records.

**Comment by jwmoss** [comment]
Fixed in version 0.2.4 Thanks @AaronG1234 for your help!
