### ISSUE TITLE
Question, NON issue

### ISSUE THREAD

**Issue by AaronG1234** [jwmoss/PSTenable#14]
Do you know how to get the Vuln Text... from the API

in the web gui, if i am in Vuln Details, i can see the actual vuln
"expected value was this", "current value is this"

i am looking to get that text for each of my criticals
(some vuln data is useless without it, especially MS family patches that in addition to files versions require a registry setting... without that info, it appears the patch is not installed, but in fact it is the setting that is missing)

**Comment by jwmoss** [comment]
I'm not sure, I wanted to look into that myself, but never got around to that.

**Comment by jwmoss** [comment]
Posted on twitter asking if others are aware, including pyTenable author.

**Comment by jwmoss** [comment]
Looks like you have to get the pluginID, and then use the `/plugin/id` endpoint to retrieve that data.

[Twitter thread](https://twitter.com/MSAdministrator/status/1196641476161216512)
[API link](https://docs.tenable.com/sccv/api/Plugin.html#PluginRESTReference-/plugin/{id})

**Comment by AaronG1234** [comment]
I added it in the pull request for pstenableseverity
When you get detailed data, one of the columns is vuln text
