### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by FriedrichWeinmann** [jwmoss/PSTenable#9]
> Invoke-PSTenableRest

TLS settings should be declared during begin, not process

Extract TLS settings into dedicated function, to avoid code duplication.

> Invoke-PSTenableTokenStatus

Unsuitable use of Write-Output

> Connect-PSTenable

Wrong check for `$Register` parameter: Should be truth content check
Otherwise this:

```
-Register:$false
```

Will cause the command to perform a register afterall!

> Get-PSTenableAssetAnalysis

Duplicate type declaration in Parameter

`$ComputerName` parameter should be of type `[PSFComputer]` not `[string]`

No reason to not accept from pipeline and process multiple computers in one call

> Get-PSTenableCVE

`$CVE` should be a `[string[]]` not a `[string]` type

Storing results, just so they can be returned in the `end` block is a bad design. Should emit them as they are reached at.

> Get-PSTenablePlugin

`$ID` should be a `[string[]]` not a `[string]` type

Storing results, just so they can be returned in the `end` block is a bad design. Should emit them as they are reached at.

> Get-PSTenablePluginFamilyWindows

Storing results, just so they can be returned in the `end` block is a bad design. Should emit them as they are reached at.

> Get-PSTenableSeverity

Data retrieval should happen during `process`

> Get-PSTenableWindowsServerJava

Data retrieval should happen during `process`

> General PSFramework Stuff:

Configuration settings should be declared & Initialized when used in modules.

e.g. during module import, execute something like this:

```powershell
Set-PSFconfig -Module PSTenable -Name Credential -Value $null -Initialize -Validation credential -Description 'The credentials used for authenticating to the Tenable server'
```

**Comment by jwmoss** [comment]
Thank you @FriedrichWeinmann! Published 0.2.3 with code review.
